export const DEFAULT_CATEGORIES = [
  // 🍽️ Dishes
  {
    name: "Pizza",
    slug: "pizza",
    icon: "🍕",
    type: "dish",
    sortOrder: 1,
  },
  {
    name: "Burger",
    slug: "burger",
    icon: "🍔",
    type: "dish",
    sortOrder: 2,
  },
  {
    name: "Biryani",
    slug: "biryani",
    icon: "🍛",
    type: "dish",
    sortOrder: 3,
  },
  {
    name: "Sandwich",
    slug: "sandwich",
    icon: "🥪",
    type: "dish",
    sortOrder: 4,
  },
  {
    name: "Rolls",
    slug: "rolls",
    icon: "🌯",
    type: "dish",
    sortOrder: 5,
  },
  {
    name: "Wraps",
    slug: "wraps",
    icon: "🌮",
    type: "dish",
    sortOrder: 6,
  },
  {
    name: "Momos",
    slug: "momos",
    icon: "🥟",
    type: "dish",
    sortOrder: 7,
  },
  {
    name: "Pasta",
    slug: "pasta",
    icon: "🍝",
    type: "dish",
    sortOrder: 8,
  },
  {
    name: "Noodles",
    slug: "noodles",
    icon: "🍜",
    type: "dish",
    sortOrder: 9,
  },
  {
    name: "Salads",
    slug: "salads",
    icon: "🥗",
    type: "dish",
    sortOrder: 10,
  },
  {
    name: "BBQ",
    slug: "bbq",
    icon: "🍖",
    type: "dish",
    sortOrder: 11,
  },
  {
    name: "Seafood",
    slug: "seafood",
    icon: "🦞",
    type: "dish",
    sortOrder: 12,
  },
  {
    name: "Ice Cream",
    slug: "ice-cream",
    icon: "🍨",
    type: "dish",
    sortOrder: 13,
  },
  {
    name: "Cakes",
    slug: "cakes",
    icon: "🎂",
    type: "dish",
    sortOrder: 14,
  },

  // 🌍 Cuisines
  {
    name: "North Indian",
    slug: "north-indian",
    icon: "🍲",
    type: "cuisine",
    sortOrder: 15,
  },
  {
    name: "South Indian",
    slug: "south-indian",
    icon: "🥥",
    type: "cuisine",
    sortOrder: 16,
  },
  {
    name: "Chinese",
    slug: "chinese",
    icon: "🥡",
    type: "cuisine",
    sortOrder: 17,
  },
  {
    name: "Italian",
    slug: "italian",
    icon: "🍝",
    type: "cuisine",
    sortOrder: 18,
  },
  {
    name: "Mexican",
    slug: "mexican",
    icon: "🌮",
    type: "cuisine",
    sortOrder: 19,
  },
  {
    name: "Thai",
    slug: "thai",
    icon: "🍜",
    type: "cuisine",
    sortOrder: 20,
  },
  {
    name: "Japanese",
    slug: "japanese",
    icon: "🍣",
    type: "cuisine",
    sortOrder: 21,
  },
  {
    name: "Korean",
    slug: "korean",
    icon: "🍱",
    type: "cuisine",
    sortOrder: 22,
  },
  {
    name: "Mughlai",
    slug: "mughlai",
    icon: "🍖",
    type: "cuisine",
    sortOrder: 23,
  },

  // 🥤 Meals / Collections
  {
    name: "Fast Food",
    slug: "fast-food",
    icon: "🍟",
    type: "meal",
    sortOrder: 24,
  },
  {
    name: "Street Food",
    slug: "street-food",
    icon: "🥙",
    type: "meal",
    sortOrder: 25,
  },
  {
    name: "Healthy Food",
    slug: "healthy-food",
    icon: "🥦",
    type: "meal",
    sortOrder: 26,
  },
  {
    name: "Vegetarian",
    slug: "vegetarian",
    icon: "🥬",
    type: "meal",
    sortOrder: 27,
  },
  {
    name: "Vegan",
    slug: "vegan",
    icon: "🌱",
    type: "meal",
    sortOrder: 28,
  },
  {
    name: "Bakery",
    slug: "bakery",
    icon: "🥐",
    type: "meal",
    sortOrder: 29,
  },
  {
    name: "Desserts",
    slug: "desserts",
    icon: "🍰",
    type: "meal",
    sortOrder: 30,
  },
  {
    name: "Beverages",
    slug: "beverages",
    icon: "🥤",
    type: "meal",
    sortOrder: 31,
  },
  {
    name: "Juices",
    slug: "juices",
    icon: "🧃",
    type: "meal",
    sortOrder: 32,
  },
  {
    name: "Coffee",
    slug: "coffee",
    icon: "☕",
    type: "meal",
    sortOrder: 33,
  },
  {
    name: "Tea",
    slug: "tea",
    icon: "🫖",
    type: "meal",
    sortOrder: 34,
  },
  {
    name: "Shakes",
    slug: "shakes",
    icon: "🥤",
    type: "meal",
    sortOrder: 35,
  },
  {
    name: "Smoothies",
    slug: "smoothies",
    icon: "🍹",
    type: "meal",
    sortOrder: 36,
  },
];